--- DATABASE
--USE master
CREATE DATABASE QUANLY_SINHVIEN
GO
USE QUANLY_SINHVIEN
GO

CREATE TABLE TBL_TRUONG(
	MATRUONG NVARCHAR(25) PRIMARY KEY,
	TENTRUONG NVARCHAR(150) NOT NULL,
	DIACHI NVARCHAR(150),
	SDT NVARCHAR(11),
	EMAIL VARCHAR(100)
)
GO

CREATE TABLE TBL_KHOA(
	MAKHOA NVARCHAR(25) PRIMARY KEY,
	TENKHOA NVARCHAR(150) NOT NULL,
	SDT NVARCHAR(11),
	MATRUONG NVARCHAR(25) NOT NULL, 
	EMAIL VARCHAR(100)
)
GO

CREATE TABLE TBL_BOMON(
	MABOMON NVARCHAR(25) PRIMARY KEY,
	TENBOMON NVARCHAR(150) NOT NULL,
	MAKHOA NVARCHAR(25)
)
GO

CREATE TABLE TBL_GIANGVIEN(
	MAGIANGVIEN NVARCHAR(25) PRIMARY KEY,
	TENGIANGVIEN NVARCHAR(150) NOT NULL,
	NGAYVAOTRUONG DATE ,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(10) CHECK (GIOITINH IN (N'Nam',N'Nữ',N'Không')),
	HOCVAN NVARCHAR(50),
	SDT NVARCHAR(11) UNIQUE,
	CCCD NVARCHAR(12) UNIQUE,
	MABOMON NVARCHAR(25),
	DANTOC NVARCHAR(30),
	TONGIAO NVARCHAR(30),
	DIACHITT NVARCHAR(150) ,
	HINHANH NVARCHAR(200),
	TRANGTHAI NVARCHAR(30) CHECK (TRANGTHAI IN (N'Đang làm',N'Nghỉ làm'))
)
GO

CREATE TABLE TBL_SINHVIEN(
	MSSV NVARCHAR(25) PRIMARY KEY,
	TENSINHVIEN NVARCHAR(150) NOT NULL,
	NGAYVAOTRUONG DATE ,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(10) CHECK (GIOITINH IN (N'Nam',N'Nữ',N'Không')),
	HOCVAN NVARCHAR(50),
	SDT NVARCHAR(11) UNIQUE,
	CCCD NVARCHAR(12) UNIQUE,
	MABOMON NVARCHAR(25),
	DANTOC NVARCHAR(30),
	TONGIAO NVARCHAR(30),
	DIACHITT NVARCHAR(150) ,
	HINHANH NVARCHAR(200),
	TRANGTHAI NVARCHAR(30) CONSTRAINT CK_TBL_SINHVIEN_TRANGTHAI CHECK  (TRANGTHAI IN (N'Đang học',N'Nghỉ học',N'Đã tốt nghiệp'))
	)
GO


CREATE TABLE TBL_MONHOC(
	MAMONHOC NVARCHAR(25) PRIMARY KEY,
	TENMONHOC NVARCHAR(150) NOT NULL,
	MAKHOA NVARCHAR(25),
	SOTC INT CONSTRAINT CK_SOTC CHECK (SOTC >= 0),
	TILEQUATRINH decimal(5,2), --- tỉ lệ điểm của điểm quá trình 0.3, 0.5, 0.4 ....
	LOAIMON NVARCHAR(30) CONSTRAINT CK_LOAIMON CHECK (LOAIMON IN (N'Lý thuyết',N'Thực hành'))
)
GO

CREATE TABLE TBL_HOCKY(
	MAHOCKY INT IDENTITY(1,1) PRIMARY KEY,
	TENHOCKY INT,
	NAMBATDAU INT,
	NAMKETTHUC INT,
	--- THỂ HIỆN HK1 -2020 -2021
)
GO

CREATE TABLE TBL_MONDANGKY(
	MAMONDANGKY INT IDENTITY(1,1) PRIMARY KEY,
	MAMONHOC NVARCHAR(25) NOT NULL,
	MAGIANGVIEN NVARCHAR(25),
	MAHOCKY INT NOT NULL,
	BATDAU DATE,
	KETTHUC DATE,
	LOPDUKIEN NVARCHAR(10) NOT NULL, -- 11DHTH4
	SISO INT
)
GO

CREATE TABLE TBL_MON_SINHVIEN_DANGKY(
	MSSV NVARCHAR(25) NOT NULL,
	MAMONDANGKY INT,
	DIEMQUATRINH DECIMAL(4,2),
	DIEMTHI DECIMAL(4,2),
	DIEMTONG DECIMAL(4,2)
)
GO



CREATE TABLE TBL_TAIKHOAN(
	MATAIKHOAN INT IDENTITY(1,1) PRIMARY KEY,
	USERNAME NVARCHAR(25) NOT NULL UNIQUE, --- LÀ MSSV HOẶC MAGV
	MATKHAU NVARCHAR(150) DEFAULT '@HUIT140'
)
GO

---- TẠO RÀNG BUỘC KHÓA NGOẠI
---- TBL_KHOA
ALTER TABLE TBL_KHOA 
	ADD CONSTRAINT FK_KHOA_TRUONG 
		FOREIGN KEY (MATRUONG) REFERENCES TBL_TRUONG (MATRUONG)
GO
----- TBL_BOMON
ALTER TABLE TBL_BOMON 
	ADD CONSTRAINT FK_TBL_BOMON_TBL_KHOA 
		FOREIGN KEY (MAKHOA) REFERENCES TBL_KHOA(MAKHOA)
GO
---- TBL_GIANGVIEN
ALTER TABLE TBL_GIANGVIEN ADD CONSTRAINT FK_TBL_GIANGVIEN_MABOMON
	FOREIGN KEY (MABOMON) REFERENCES TBL_BOMON(MABOMON)
GO

----TBL_SINHVIEN
ALTER TABLE TBL_SINHVIEN ADD CONSTRAINT FK_TBL_SINHVIEN_TBL_BOMON
	FOREIGN KEY (MABOMON) REFERENCES TBL_BOMON(MABOMON)
GO

---- TBL_MONHOC
ALTER TABLE TBL_MONHOC ADD CONSTRAINT FK_TBL_MONHOC_TBL_KHOA 
		FOREIGN KEY (MAKHOA) REFERENCES TBL_KHOA(MAKHOA)
GO

----- TBL_MONDANGKY
ALTER TABLE TBL_MONDANGKY ADD CONSTRAINT FK_TBL_MONDANGKY_TBL_GIANGVIEN
	FOREIGN KEY (MAGIANGVIEN) REFERENCES TBL_GIANGVIEN(MAGIANGVIEN)
GO
ALTER TABLE TBL_MONDANGKY ADD CONSTRAINT FK_TBL_MONDANGKY_TBL_MONHOC
	FOREIGN KEY (MAMONHOC) REFERENCES TBL_MONHOC(MAMONHOC)
GO
ALTER TABLE TBL_MONDANGKY ADD CONSTRAINT FK_TBL_MONDANGKY_TBL_HOCKY
	FOREIGN KEY (MAHOCKY) REFERENCES TBL_HOCKY(MAHOCKY)
GO

----- TBL_MON_SINHVIEN_DANGKY
ALTER TABLE  TBL_MON_SINHVIEN_DANGKY ADD CONSTRAINT FK_TBL_MON_SINHVIEN_DANGKY_TBL_MONDANGKY
	FOREIGN KEY (MAMONDANGKY) REFERENCES TBL_MONDANGKY(MAMONDANGKY)
GO
ALTER TABLE  TBL_MON_SINHVIEN_DANGKY ADD CONSTRAINT FK_TBL_MON_SINHVIEN_DANGKY_TBL_SINHVIEN
	FOREIGN KEY (MSSV) REFERENCES TBL_SINHVIEN(MSSV)
GO
---- TBL_TAIKHOAN
ALTER TABLE TBL_TAIKHOAN ADD CONSTRAINT FK_TBL_TAIKHOAN_TBL_SINHVIEN
	FOREIGN KEY (USERNAME) REFERENCES TBL_SINHVIEN(MSSV)
GO

ALTER TABLE TBL_TAIKHOAN ADD CONSTRAINT FK_TBL_TAIKHOAN_TBL_GIANGVIEN
	FOREIGN KEY (USERNAME) REFERENCES TBL_GIANGVIEN(MAGIANGVIEN)
GO








