--- TBL_TRUONG
INSERT INTO TBL_TRUONG (MATRUONG, TENTRUONG, DIACHI, SDT, EMAIL) 
VALUES ('TR001', N'Trường Đại học ABC', N'123 Đường ABC, TP. HCM', '0123456789', 'abc@university.com');

---- TBL_KHOA
INSERT INTO TBL_KHOA (MAKHOA, TENKHOA, SDT, MATRUONG, EMAIL) 
VALUES ('KH001', N'Khoa Khoa học máy tính', '0987654321', 'TR001', 'khoa.khmt@university.com');

--- TBL_KHOA
INSERT INTO TBL_BOMON (MABOMON, TENBOMON, MAKHOA) 
VALUES ('BM001', N'Bộ môn Khoa học máy tính', 'KH001');

---- TBL_BOMON
INSERT INTO TBL_BOMON (MABOMON, TENBOMON, MAKHOA) 
VALUES ('BM001', N'Bộ môn Khoa học máy tính', 'KH001');

--- TBL_GIANGVIEN
INSERT INTO TBL_GIANGVIEN (MAGIANGVIEN, TENGIANGVIEN, NGAYVAOTRUONG, NGAYSINH, GIOITINH, HOCVAN, SDT, CCCD, MABOMON, DANTOC, TONGIAO, DIACHITT, HINHANH, TRANGTHAI) 
VALUES ('GV001', N'Nguyễn Văn A', '2020-01-01', '1980-05-20', N'Nam', N'Tiến sĩ', '0123456789', '123456789012', 'BM001', N'Kinh', N'Thập tự', N'123 Đường ABC, TP. HCM', 'avatar.jpg', N'Đang làm');





















